name: todoem
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  flutter_bloc: ^8.1.1
  firebase_ui_auth: ^1.0.0-dev.0
  equatable: ^2.0.5
  gap: ^2.0.0
  jiffy: ^5.0.0
  flutter_slidable: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.2.11
  # workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.0

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 19 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/light.png

  color_dark: "#000000"
  image_dark: assets/splash/dark.png

  ios: false
  web: false
